import type { IQuestionBankItem } from "@/lib/questions/question-bank.ts";

export const GENERAL_QUESTION_BANK: IQuestionBankItem[] = [
  {
    id: "why-this-company",
    category: "general",
    questions: [
      "Why do you want to work here?",
      "Why this company?",
      "What attracted you to our organization?",
      "Why are you interested in working for us?",
    ],
    suggestions: "Connect specific aspects of the organization to your interests and experience. Show that you understand what the company does rather than giving a generic answer.",
  },
  {
    id: "why-this-role",
    category: "general",
    questions: [
      "Why do you want this role?",
      "Why are you interested in this position?",
      "What attracted you to this job?",
      "Why did you apply for this position?",
    ],
    suggestions: "Connect the responsibilities of the role to your experience, interests, and next step. Focus on what you can contribute and what you want to develop.",
  },
  {
    id: "why-hire-you",
    category: "general",
    questions: [
      "Why should we hire you?",
      "Why are you the right person for this role?",
      "What makes you a strong fit for this position?",
      "Why do you think you'd succeed here?",
    ],
    suggestions: "Summarize two or three capabilities that directly match the role and support each with evidence. Keep it focused on the employer's needs rather than generic self-praise.",
  },
  {
    id: "strengths",
    category: "general",
    questions: [
      "What are your strengths?",
      "What are your greatest strengths?",
      "What are you particularly good at?",
      "Which strengths would you bring to this role?",
    ],
    suggestions: "Choose strengths relevant to the role and support them with brief evidence. Specific behaviors and outcomes are more convincing than a list of adjectives.",
  },
  {
    id: "weaknesses",
    category: "general",
    questions: [
      "What are your weaknesses?",
      "What is an area you need to improve?",
      "What would you like to get better at?",
      "What is one professional weakness you're working on?",
    ],
    suggestions: "Choose a genuine, manageable development area and explain what you are doing about it. Avoid disguised strengths and avoid weaknesses that directly undermine an essential job requirement.",
  },
  {
    id: "five-years",
    category: "general",
    questions: [
      "Where do you see yourself in five years?",
      "What are your long-term career goals?",
      "Where would you like your career to be in five years?",
      "What do you hope to be doing several years from now?",
    ],
    suggestions: "Describe a plausible direction rather than a rigid prediction. Connect your development goals to the kind of responsibilities and contribution you want to grow toward.",
  },
  {
    id: "career-goals",
    category: "general",
    questions: [
      "What are your career goals?",
      "What do you want to accomplish in your career?",
      "What are you working toward professionally?",
      "What are your long-term professional ambitions?",
    ],
    suggestions: "Give a clear direction and explain why it matters to you. Keep the answer compatible with the role without pretending to have your entire career mapped out.",
  },
  {
    id: "why-leaving",
    category: "general",
    questions: [
      "Why are you leaving your current job?",
      "Why do you want to leave your company?",
      "Why are you looking for a new opportunity?",
      "What prompted you to start looking for another job?",
    ],
    suggestions: "Stay factual and professional. Focus on what you are moving toward rather than criticizing your current or former employer.",
  },
  {
    id: "employment-gap",
    category: "general",
    questions: [
      "Can you explain this gap in your employment?",
      "Why was there a gap between these jobs?",
      "What were you doing during your employment gap?",
      "Can you tell me about the period when you weren't working?",
    ],
    suggestions: "Answer directly and briefly. Explain what you were doing during the period and mention relevant learning, responsibilities, or circumstances without becoming defensive.",
  },
  {
    id: "education",
    category: "general",
    questions: [
      "Tell me about your educational background.",
      "Walk me through your education.",
      "Why did you choose your field of study?",
      "How has your education prepared you for this role?",
    ],
    suggestions: "Highlight the parts of your education that are relevant to the role and explain choices or transitions when useful. Avoid reciting your entire academic history.",
  },
  {
    id: "career-change",
    category: "general",
    questions: [
      "Why are you changing careers?",
      "Why did you decide to move into this field?",
      "What prompted your career change?",
      "Why are you pursuing a different type of role?",
    ],
    suggestions: "Explain the transition as a coherent story: what you learned from the previous path, what attracted you to the new one, and what you've done to prepare.",
  },
  {
    id: "overqualified",
    category: "general",
    questions: [
      "Do you think you're overqualified for this role?",
      "Why are you applying for a position below your experience level?",
      "Would this role be too junior for you?",
      "Why this role given your background?",
    ],
    suggestions: "Address the concern directly and explain why the actual responsibilities, environment, subject matter, or growth path make the role appropriate for you.",
  },
  {
    id: "underqualified",
    category: "general",
    questions: [
      "You don't have all the experience listed. Why should we consider you?",
      "How would you handle the parts of this role you haven't done before?",
      "You lack experience in X. How would you approach that?",
      "What makes you a fit despite the gaps in your background?",
    ],
    suggestions: "Acknowledge the gap without apologizing for it. Connect transferable experience to the requirement and explain how you would close the remaining gap.",
  },
  {
    id: "salary-expectations",
    category: "general",
    questions: [
      "What are your salary expectations?",
      "What compensation are you looking for?",
      "What salary range would you consider?",
      "What are your compensation expectations for this role?",
    ],
    suggestions: "Research the market and role beforehand. Give a reasonable range when appropriate and consider the full compensation package and role scope rather than focusing only on a single number.",
  },
  {
    id: "start-date",
    category: "general",
    questions: [
      "When can you start?",
      "What is your availability?",
      "How soon could you join?",
      "When would you be available to begin?",
    ],
    suggestions: "Give your realistic availability. If you have notice, commitments, or constraints, state them clearly and avoid promising a date you cannot meet.",
  },
  {
    id: "relocation",
    category: "general",
    questions: [
      "Are you willing to relocate?",
      "Would you relocate for this role?",
      "Are you open to moving?",
      "Would location be an issue for you?",
    ],
    suggestions: "State your actual flexibility and any important constraints. If conditional, explain what would make relocation workable.",
  },
  {
    id: "remote-hybrid",
    category: "general",
    questions: [
      "Are you comfortable working remotely?",
      "What is your preferred work arrangement?",
      "How do you feel about hybrid work?",
      "Would you be willing to work from the office?",
    ],
    suggestions: "Answer according to your actual preferences while showing how you maintain communication, accountability, and productivity in the proposed arrangement.",
  },
  {
    id: "work-authorization",
    category: "general",
    questions: [
      "Are you authorized to work here?",
      "Will you require sponsorship?",
      "Do you have the right to work in this country?",
      "What is your work authorization status?",
    ],
    suggestions: "Answer the legal or administrative question directly and accurately. Provide only the information relevant to the employer's question.",
  },
  {
    id: "job-search",
    category: "general",
    questions: [
      "Are you interviewing elsewhere?",
      "Where else are you in the interview process?",
      "Are you considering other offers?",
      "What other opportunities are you exploring?",
    ],
    suggestions: "Be truthful without oversharing confidential details. You can describe the types of roles or stages involved without turning the answer into a negotiation tactic.",
  },
  {
    id: "how-found-us",
    category: "general",
    questions: [
      "How did you hear about this position?",
      "How did you find us?",
      "Where did you see this job?",
      "What made you come across our company?",
    ],
    suggestions: "Give the actual source and, if useful, briefly mention what prompted you to investigate the opportunity further.",
  },
  {
    id: "what-do-you-know",
    category: "general",
    questions: [
      "What do you know about our company?",
      "What do you know about us?",
      "What have you learned about the organization?",
      "How familiar are you with our company?",
    ],
    suggestions: "Demonstrate basic research about the company's products, customers, market, or mission. Focus on accurate, relevant facts rather than memorized trivia.",
  },
  {
    id: "company-interest",
    category: "general",
    questions: [
      "What interests you most about our company?",
      "What stands out to you about us?",
      "What do you find interesting about our organization?",
      "What specifically attracted you to us?",
    ],
    suggestions: "Choose one or two specific aspects and explain why they matter to you. Avoid repeating marketing language without showing your own reasoning.",
  },
  {
    id: "culture-fit",
    category: "general",
    questions: [
      "What kind of work environment do you thrive in?",
      "What type of company culture suits you?",
      "What environment brings out your best work?",
      "What do you value in a workplace?",
    ],
    suggestions: "Describe concrete working conditions and behaviors that help you perform well. Avoid simply listing fashionable culture words.",
  },
  {
    id: "ideal-manager",
    category: "general",
    questions: [
      "What do you look for in a manager?",
      "What management style works best for you?",
      "How do you like to be managed?",
      "What makes a good manager for you?",
    ],
    suggestions: "Describe the communication, autonomy, feedback, and support you work best with. Show adaptability rather than requiring one exact management style.",
  },
  {
    id: "ideal-job",
    category: "general",
    questions: [
      "What does your ideal job look like?",
      "What would your ideal role involve?",
      "What are you looking for in your next job?",
      "What would make a job a great fit for you?",
    ],
    suggestions: "Prioritize responsibilities, learning, collaboration, and impact that genuinely matter to you. Keep the answer compatible with the role you are discussing.",
  },
  {
    id: "motivates-you",
    category: "general",
    questions: [
      "What motivates you?",
      "What are you passionate about professionally?",
      "What kind of work are you genuinely excited by?",
      "What motivates you to do your best work?",
    ],
    suggestions: "Name a few genuine drivers — the work you find energizing and the outcomes you care about — and connect them to situations where they produced strong work. Avoid a generic answer that only sounds impressive, and don't lean on external rewards unless they are genuinely central.",
  },
  {
    id: "what-demotivates",
    category: "general",
    questions: [
      "What demotivates you?",
      "What kinds of work frustrate you?",
      "What makes it difficult for you to stay engaged?",
      "What workplace situations do you find demotivating?",
    ],
    suggestions: "Choose a manageable workplace issue and explain how you handle it constructively. Avoid presenting ordinary job responsibilities as beneath you.",
  },
  {
    id: "definition-success",
    category: "general",
    questions: [
      "What does success mean to you?",
      "How do you define success?",
      "What does professional success look like to you?",
      "How do you know when you've done a good job?",
    ],
    suggestions: "Give a definition grounded in outcomes, learning, contribution, or other genuine values, then support it with an example.",
  },
  {
    id: "definition-failure",
    category: "general",
    questions: [
      "How do you define failure?",
      "What does failure mean to you?",
      "When do you consider a project unsuccessful?",
      "How do you evaluate failure?",
    ],
    suggestions: "Distinguish between an undesirable outcome and a failure to learn or respond. Explain how you use setbacks to improve future decisions.",
  },
  {
    id: "why-you",
    category: "general",
    questions: [
      "What makes you different from other candidates?",
      "What would you bring that others might not?",
      "What is distinctive about your background?",
      "What sets you apart?",
    ],
    suggestions: "Focus on a specific combination of experience, perspective, or capability that is relevant to the role. Avoid making claims about other candidates.",
  },
  {
    id: "career-priority",
    category: "general",
    questions: [
      "What matters most to you in your next job?",
      "What are your top priorities when choosing a role?",
      "What are you looking for in your next employer?",
      "What would make you accept an offer?",
    ],
    suggestions: "Identify a few genuine priorities and distinguish essentials from preferences. Consider responsibilities, growth, environment, and practical constraints.",
  },
];
