import { useMemo, useState } from "react";
import { toast } from "sonner";
import { type IJob, useJobsAll } from "@/api/jobs";
import type { IResume } from "@/api/resumes";
import {
  type TAtsScore,
  useAtsScoreEntries,
  useGetResumes,
  useScoreResume,
} from "@/api/resumes";
import { AiDialog } from "@/components/common/ai/AiDialog.tsx";
import { AppCombobox } from "@/components/common/form/combobox/AppCombobox.tsx";
import { ATSReviewCard } from "@/components/resume/ats/ATSReviewCard.tsx";
import { Button } from "@/components/ui/button.tsx";
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card.tsx";
import type { IAtsCacheEntry, IAtsScoreFilter } from "@/lib/indexdb.ts";

interface IProps {
  job?: IJob;
}

const MAX_DEFAULT_ENTRIES = 5;

const toFullScore = (entry: IAtsCacheEntry): TAtsScore => ({
  overall: entry.overall,
  categories: entry.categories,
  recommendations: entry.recommendations,
  matchedKeywords: [],
  missingKeywords: [],
  tailoringNotes: "",
});

export const ATSReview = ({ job }: Readonly<IProps>) => {
  const { data: jobsData } = useJobsAll();
  const { data: resumesData } = useGetResumes();
  const jobs = jobsData ?? [];
  const resumes = resumesData ?? [];
  const scoreMutation = useScoreResume();

  const [selectedJobId, setSelectedJobId] = useState<string | null>(null);
  const [selectedResumeId, setSelectedResumeId] = useState<string | null>(null);
  const [aiDialogOpen, setAiDialogOpen] = useState(false);

  const jobId = job ? job.id : selectedJobId;

  const filter = useMemo<IAtsScoreFilter>(() => {
    if (job) {
      return { jobId: job.id };
    }
    return {
      ...(selectedJobId ? { jobId: selectedJobId } : {}),
      ...(selectedResumeId ? { resumeId: selectedResumeId } : {}),
    };
  }, [job, selectedJobId, selectedResumeId]);

  const { data = [] } = useAtsScoreEntries(filter);
  const hasFilter =
    job !== undefined || selectedJobId !== null || selectedResumeId !== null;
  const entries = hasFilter ? data : data.slice(0, MAX_DEFAULT_ENTRIES);

  const jobMap = useMemo(() => new Map(jobs.map((j) => [j.id, j])), [jobs]);
  const resumeMap = useMemo(
    () => new Map(resumes.map((r) => [r.id, r])),
    [resumes]
  );

  const handleOpenDialog = () => {
    setAiDialogOpen(true);
  };

  const closeDialog = () => setAiDialogOpen(false);

  const handleGenerate = async (provider: string, model?: string) => {
    if (!(jobId && selectedResumeId)) {
      toast.error("Please select a job and resume");
      return;
    }
    try {
      await scoreMutation.mutateAsync({
        jobId,
        resumeId: selectedResumeId,
        provider,
        model,
      });

      toast.success("AI resume review generated");
    } catch {
      toast.error("Failed to generate AI resume review");
    } finally {
      closeDialog();
    }
  };

  const handleJobChange = (value: string | number | null) =>
    setSelectedJobId(value === null ? null : String(value));

  const jobToOption = (j: IJob) => ({
    value: j.id,
    label: `${j.title} @ ${j.companyName}`,
  });

  const handleResumeChange = (value: string | number | null) =>
    setSelectedResumeId(value === null ? null : String(value));

  const resumeToOption = (r: IResume) => ({ value: r.id, label: r.name });

  return (
    <Card className="px-1">
      <CardHeader className="border-b">
        <CardTitle className="flex items-center gap-2">Resume Review</CardTitle>
        <CardDescription>
          Generated by comparing your resume against selected job with AI.
          Results are cached locally and never stored on the server.
        </CardDescription>
        <CardAction>
          <Button onClick={handleOpenDialog} size="sm">
            New Review
          </Button>
        </CardAction>
      </CardHeader>
      <CardContent className="flex flex-col gap-5">
        <div className="grid gap-4 sm:grid-cols-2">
          {job ? null : (
            <AppCombobox
              data={jobs}
              label="Job"
              onChange={handleJobChange}
              placeholder="Select a job..."
              toOption={jobToOption}
              value={selectedJobId}
            />
          )}

          {job ? null : (
            <AppCombobox
              data={resumes}
              label="Resume"
              onChange={handleResumeChange}
              placeholder="Select a resume..."
              toOption={resumeToOption}
              value={selectedResumeId}
            />
          )}
        </div>

        {entries.length === 0 ? (
          <CardDescription className="text-center italic">
            No saved scores for selection yet. Pick a job and resume, then tap
            “New Review” to run the AI resume review.
          </CardDescription>
        ) : (
          <div className="flex flex-col gap-5">
            {entries.map((entry) => {
              const relatedJob = jobMap.get(entry.jobId);
              const relatedResume = resumeMap.get(entry.resumeId);
              return (
                <ATSReviewCard
                  companyName={relatedJob?.companyName}
                  jobTitle={relatedJob?.title}
                  key={`${entry.jobId}|${entry.resumeId}`}
                  resumeName={relatedResume?.name}
                  score={toFullScore(entry)}
                />
              );
            })}
          </div>
        )}
      </CardContent>

      <AiDialog
        description="Pick a resume to score against the selected job description and company."
        executeDisabled={!(selectedResumeId && selectedJobId)}
        executeLabel="Generate"
        isLoading={scoreMutation.isPending}
        onExecute={handleGenerate}
        onOpenChange={setAiDialogOpen}
        open={aiDialogOpen}
        title="Generate AI Resume Review"
      >
        <AppCombobox
          data={jobs}
          label="Job"
          onChange={handleJobChange}
          placeholder="Select a job..."
          toOption={jobToOption}
          value={selectedJobId}
        />

        <AppCombobox
          data={resumes}
          label="Resume"
          onChange={handleResumeChange}
          placeholder="Select a resume..."
          toOption={resumeToOption}
          value={selectedResumeId}
        />
      </AiDialog>
    </Card>
  );
};
